package Bandejas;
import Mensaje.mensajeScreen;
import Modelo.conexion;
import PanelFondo.panelFondo;
import javax.swing.DefaultListModel;

public class bandejaScreen extends javax.swing.JFrame {
    logInScreen win;
    conexion con;
    String user,user_id;
    String[][] msgs;
    
    /**
     * Creates new form bandejaScreen
     */
    public bandejaScreen() {
        con=new conexion();
        this.setContentPane(new panelFondo("/image/bg.jpg"));
        initComponents();
    }
    
    public bandejaScreen(logInScreen win,String user){
        con=new conexion();
        this.user=user;
        this.win=win;
        this.setContentPane(new panelFondo("/image/bg.jpg"));
        initComponents();
        String[] name=user.split("@");
        this.mensajeBienvenida.setText("Bienvenid@ "+name[0]);
        loadData();
    }
    
    // Carga de datos, obtencion del id del usuario, asi como los mensajes que estan relacionados con el.
    private void loadData(){
        String[][] aux=con.leerDatos("usuarios","id", "user='"+this.user+"'");
        this.user_id=aux[0][0];
        msgs=con.leerDatos("mensajes","id,emisor,destinatario,asunto,mensaje,user_id", "user_id='"+this.user_id+"'");
        loadAsuntos();
        
    }
    
    private void loadAsuntos(){
        DefaultListModel model=new DefaultListModel();
            for(int i=0;i<msgs.length;i++){
                model.addElement(msgs[i][3]);
            }
        this.listaMensajes.setModel(model);
    }
    
    private void loadMensajes(){
        this.areaMensaje.setText("De: "+msgs[this.listaMensajes.getSelectedIndex()][1]+
                "\nPara: "+msgs[this.listaMensajes.getSelectedIndex()][2]+
                "\nAsunto: "+msgs[this.listaMensajes.getSelectedIndex()][3]+
                "\n\n"+msgs[this.listaMensajes.getSelectedIndex()][4]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaMensajes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaMensaje = new javax.swing.JTextArea();
        mensajeBienvenida = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Bandeja de entrada");
        setMinimumSize(new java.awt.Dimension(740, 540));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        listaMensajes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMensajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaMensajes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 200, 380);

        areaMensaje.setColumns(20);
        areaMensaje.setLineWrap(true);
        areaMensaje.setRows(5);
        jScrollPane2.setViewportView(areaMensaje);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(220, 60, 500, 380);

        mensajeBienvenida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mensajeBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        mensajeBienvenida.setText("Bienvenido ");
        getContentPane().add(mensajeBienvenida);
        mensajeBienvenida.setBounds(10, 10, 700, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Enviar Mensaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 460, 170, 27);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mensajeScreen win=new mensajeScreen();
        win.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        win.show();
        this.dispose();
    }//GEN-LAST:event_formComponentHidden

    private void listaMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMensajesMouseClicked
        this.loadMensajes();
    }//GEN-LAST:event_listaMensajesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bandejaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bandejaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bandejaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bandejaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bandejaScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaMensajes;
    private javax.swing.JLabel mensajeBienvenida;
    // End of variables declaration//GEN-END:variables
}
